title: "Cherry's Digital Space 🍒"
default_author: "Cherryleafroad"
description: "When all else fails ... reboot."

google_analytics: G-QY70XMH6JE

baseurl: /
url: http://cherryleafroad.github.io

# place all your links here
modernist:
  social_links:
    #twitter: jekyllrb
    github:  cherryleafroad
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

theme: jekyll-theme-modernist

exclude: ["Gemfile", "Gemfile.lock", ".github/", ".idea/", ".gems/", "README.md", ".ruby-version", "vendor"]

rss: rss

show_excerpts: 1
excerpt_separator: <!--more-->
show_tags: true

collections_dir: collections
collections:
  posts:
    output: true
    permalink: /:categories/:title
  authors:
    permalink: /author/:name/
  tags:
    permalink: /tag/:name/
  categories:
    permalink: /category/:name/


autopages:
  enabled: true

  authors:
    layouts:
      - author-page.html
    enabled: true
    # key to match against to filter posts
    indexkey: author
    filter_collection: true

  tags:
    layouts:
      - tag-page.html
    enabled: true

  categories:
    layouts:
      - category-page.html
    enabled: true


sass:
  style: compressed

markdown: kramdown

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-avatar
  - jekyll-paginate-v2

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      tags:

pagination:
  enabled: true

  debug: false

  collection: 'posts'

  per_page: 5

  permalink: '/page/:num'
  sort_reverse: true

  title: ':title'

  limit: 0

  sort_field: 'date'

  trail:
    before: 2
    after: 2
