name: Generate new tags

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Generate new tags
        id: gentags
        run: ./.github/deps/generate-tags.ps1

      - name: Create Pull Request
        id: cpr
        if: steps.gentags.outputs.new-tags == 'True'
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          commit-message: Added new tags -> ${{ steps.gentags.new-tags-added }}
          signoff: false
          branch: tags-update
          delete-branch: true
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          title: 'Added new tags -> ${{ steps.gentags.new-tags-added }}'
          body: |
            Hey there!
            
            It seems you just added some new tags to your blog post.
            These were the new tags: ${{ steps.gentags.new-tags-added }}
            
            I went ahead and generated your tag files for you. :wink:
            
            **_[ This was automatically generated by github-actions[bot] ]_**
          draft: false

      - name: Enable Pull Request Automerge
        if: steps.gentags.outputs.new-tags == 'True'
        uses: peter-evans/enable-pull-request-automerge@v2
        with:
          token: ${{ secrets.REPO_SCOPED_TOKEN }}
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          merge-method: rebase
