name: Build + Deploy Github Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  github-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Update tags
        id: gentags
        shell: pwsh
        run: ./.github/deps/update-collections.ps1

      - uses: helaili/jekyll-action@v2
        env:
          GITHUB_TOKEN: ${{ GITHUB_TOKEN }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
